// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndsklmrsfhuenbmusbez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kc2tsbXJzZmh1ZW5ibXVzYmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MjkyMjEsImV4cCI6MjA4OTUwNTIyMX0.iJ07b2VHi-wKWbkKKkbnMBhK3hehl2huXsMn6RhhQCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});